-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: Feb 11, 2017 at 03:45 PM
-- Server version: 5.6.35
-- PHP Version: 7.0.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `spa`
--

-- --------------------------------------------------------

--
-- Table structure for table `wp_posts`
--

CREATE TABLE `wp_posts` (
  `ID` bigint(20) UNSIGNED NOT NULL,
  `post_author` bigint(20) UNSIGNED NOT NULL DEFAULT '0',
  `post_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_title` text COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_excerpt` text COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_status` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'publish',
  `comment_status` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'open',
  `ping_status` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'open',
  `post_password` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',
  `post_name` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',
  `to_ping` text COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `pinged` text COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content_filtered` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_parent` bigint(20) UNSIGNED NOT NULL DEFAULT '0',
  `guid` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',
  `menu_order` int(11) NOT NULL DEFAULT '0',
  `post_type` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'post',
  `post_mime_type` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',
  `comment_count` bigint(20) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

--
-- Dumping data for table `wp_posts`
--

INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(1, 1, '2017-02-11 12:35:27', '2017-02-11 12:35:27', 'Welcome to WordPress. This is your first post. Edit or delete it, then start writing!', 'Hello world!', '', 'publish', 'open', 'open', '', 'hello-world', '', '', '2017-02-11 12:35:27', '2017-02-11 12:35:27', '', 0, 'http://localhost:8888/SPA/?p=1', 0, 'post', '', 1),
(2, 1, '2017-02-11 12:35:27', '2017-02-11 12:35:27', 'This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:\n\n<blockquote>Hi there! I\'m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin\' caught in the rain.)</blockquote>\n\n...or something like this:\n\n<blockquote>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</blockquote>\n\nAs a new WordPress user, you should go to <a href=\"http://localhost:8888/SPA/wp-admin/\">your dashboard</a> to delete this page and create new pages for your content. Have fun!', 'Sample Page', '', 'publish', 'closed', 'open', '', 'sample-page', '', '', '2017-02-11 12:35:27', '2017-02-11 12:35:27', '', 0, 'http://localhost:8888/SPA/?page_id=2', 0, 'page', '', 0),
(3, 1, '2017-02-11 12:35:48', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2017-02-11 12:35:48', '0000-00-00 00:00:00', '', 0, 'http://localhost:8888/SPA/?p=3', 0, 'post', '', 0),
(4, 1, '2017-02-11 12:57:43', '2017-02-11 12:57:43', '{\n    \"wp-experts::smof_data[main_logo]\": {\n        \"value\": {\n            \"url\": \"http://localhost:8888/SPA/wp-content/uploads/2017/02/LogoColorTextRight.jpeg\",\n            \"id\": \"5\",\n            \"height\": \"200\",\n            \"width\": \"200\",\n            \"thumbnail\": \"\"\n        },\n        \"type\": \"theme_mod\",\n        \"user_id\": 1\n    },\n    \"wp-experts::smof_data[sticky_logo]\": {\n        \"value\": {\n            \"url\": \"http://localhost:8888/SPA/wp-content/uploads/2017/02/LogoColorNoText.jpeg\",\n            \"id\": \"6\",\n            \"height\": \"200\",\n            \"width\": \"200\",\n            \"thumbnail\": \"\"\n        },\n        \"type\": \"theme_mod\",\n        \"user_id\": 1\n    }\n}', '', '', 'trash', 'closed', 'closed', '', '6982b478-c4c2-4966-9db5-8a6a59e7d1b4', '', '', '2017-02-11 12:57:43', '2017-02-11 12:57:43', '', 0, 'http://localhost:8888/SPA/?p=4', 0, 'customize_changeset', '', 0),
(5, 1, '2017-02-11 12:57:15', '2017-02-11 12:57:15', '', 'LogoColorTextRight', '', 'inherit', 'open', 'closed', '', 'logocolortextright', '', '', '2017-02-11 12:57:15', '2017-02-11 12:57:15', '', 0, 'http://localhost:8888/SPA/wp-content/uploads/2017/02/LogoColorTextRight.jpeg', 0, 'attachment', 'image/jpeg', 0),
(6, 1, '2017-02-11 12:57:31', '2017-02-11 12:57:31', '', 'LogoColorNoText', '', 'inherit', 'open', 'closed', '', 'logocolornotext', '', '', '2017-02-11 12:57:31', '2017-02-11 12:57:31', '', 0, 'http://localhost:8888/SPA/wp-content/uploads/2017/02/LogoColorNoText.jpeg', 0, 'attachment', 'image/jpeg', 0),
(7, 1, '2017-02-11 13:13:40', '2017-02-11 13:13:40', '{\n    \"wp-experts::smof_data[main_logo]\": {\n        \"value\": {\n            \"url\": \"http://localhost:8888/SPA/wp-content/uploads/2017/02/LogoColorTextRight-1.png\",\n            \"id\": \"9\",\n            \"height\": \"200\",\n            \"width\": \"200\",\n            \"thumbnail\": \"\"\n        },\n        \"type\": \"theme_mod\",\n        \"user_id\": 1\n    },\n    \"wp-experts::smof_data[sticky_logo]\": {\n        \"value\": {\n            \"url\": \"http://localhost:8888/SPA/wp-content/uploads/2017/02/LogoColorNoText-1.png\",\n            \"id\": \"8\",\n            \"height\": \"200\",\n            \"width\": \"200\",\n            \"thumbnail\": \"\"\n        },\n        \"type\": \"theme_mod\",\n        \"user_id\": 1\n    }\n}', '', '', 'trash', 'closed', 'closed', '', 'db80de37-989e-479a-a3e8-262f6ae43c05', '', '', '2017-02-11 13:13:40', '2017-02-11 13:13:40', '', 0, 'http://localhost:8888/SPA/?p=7', 0, 'customize_changeset', '', 0),
(8, 1, '2017-02-11 13:13:16', '2017-02-11 13:13:16', '', 'LogoColorNoText', '', 'inherit', 'open', 'closed', '', 'logocolornotext-2', '', '', '2017-02-11 13:13:16', '2017-02-11 13:13:16', '', 0, 'http://localhost:8888/SPA/wp-content/uploads/2017/02/LogoColorNoText-1.png', 0, 'attachment', 'image/png', 0),
(9, 1, '2017-02-11 13:13:17', '2017-02-11 13:13:17', '', 'LogoColorTextRight', '', 'inherit', 'open', 'closed', '', 'logocolortextright-2', '', '', '2017-02-11 13:13:17', '2017-02-11 13:13:17', '', 0, 'http://localhost:8888/SPA/wp-content/uploads/2017/02/LogoColorTextRight-1.png', 0, 'attachment', 'image/png', 0),
(10, 1, '2017-02-11 13:22:21', '2017-02-11 13:22:21', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce egestas dui quis tellus pharetra finibus. Suspendisse consequat maximus rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mattis varius posuere. Proin id sollicitudin eros. Maecenas consectetur leo nec orci finibus, laoreet semper libero molestie. Nulla sapien sapien, feugiat id arcu nec, vestibulum ornare magna. Sed orci neque, finibus nec volutpat et, dapibus ac lorem. Vivamus molestie eros consectetur augue volutpat porttitor. Suspendisse vitae pulvinar felis, eget mollis ante.\r\n\r\nIn nibh tellus, tristique sit amet sem non, egestas ullamcorper neque. Curabitur ullamcorper quam eget sapien vehicula, ut faucibus sapien porta. Nullam ornare eu justo vehicula fringilla. Integer ante odio, pellentesque sit amet posuere eget, congue in elit. Aenean tellus elit, accumsan quis consectetur eu, pharetra vel diam. Donec semper dignissim tortor, eu iaculis sapien bibendum nec. Maecenas ut nisi commodo, tempor eros nec, finibus urna. Praesent ornare urna nec velit tempus, quis sagittis leo fermentum. Fusce maximus, ligula et imperdiet pulvinar, nisl velit consectetur augue, ut porta enim eros vitae arcu. Quisque nunc metus, molestie sit amet scelerisque ut, sollicitudin sed mauris. Donec quis purus nulla. Quisque eleifend ullamcorper quam vel convallis. Praesent posuere, arcu eget semper interdum, tellus magna feugiat eros, non elementum lectus elit in neque. Phasellus pellentesque nisi ac lacus ornare interdum. Maecenas in pharetra lectus.', 'About', '', 'publish', 'closed', 'closed', '', 'about', '', '', '2017-02-11 13:22:21', '2017-02-11 13:22:21', '', 0, 'http://localhost:8888/SPA/?page_id=10', 0, 'page', '', 0),
(11, 1, '2017-02-11 13:22:21', '2017-02-11 13:22:21', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce egestas dui quis tellus pharetra finibus. Suspendisse consequat maximus rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mattis varius posuere. Proin id sollicitudin eros. Maecenas consectetur leo nec orci finibus, laoreet semper libero molestie. Nulla sapien sapien, feugiat id arcu nec, vestibulum ornare magna. Sed orci neque, finibus nec volutpat et, dapibus ac lorem. Vivamus molestie eros consectetur augue volutpat porttitor. Suspendisse vitae pulvinar felis, eget mollis ante.\r\n\r\nIn nibh tellus, tristique sit amet sem non, egestas ullamcorper neque. Curabitur ullamcorper quam eget sapien vehicula, ut faucibus sapien porta. Nullam ornare eu justo vehicula fringilla. Integer ante odio, pellentesque sit amet posuere eget, congue in elit. Aenean tellus elit, accumsan quis consectetur eu, pharetra vel diam. Donec semper dignissim tortor, eu iaculis sapien bibendum nec. Maecenas ut nisi commodo, tempor eros nec, finibus urna. Praesent ornare urna nec velit tempus, quis sagittis leo fermentum. Fusce maximus, ligula et imperdiet pulvinar, nisl velit consectetur augue, ut porta enim eros vitae arcu. Quisque nunc metus, molestie sit amet scelerisque ut, sollicitudin sed mauris. Donec quis purus nulla. Quisque eleifend ullamcorper quam vel convallis. Praesent posuere, arcu eget semper interdum, tellus magna feugiat eros, non elementum lectus elit in neque. Phasellus pellentesque nisi ac lacus ornare interdum. Maecenas in pharetra lectus.', 'About', '', 'inherit', 'closed', 'closed', '', '10-revision-v1', '', '', '2017-02-11 13:22:21', '2017-02-11 13:22:21', '', 10, 'http://localhost:8888/SPA/2017/02/11/10-revision-v1/', 0, 'revision', '', 0),
(12, 1, '2017-02-11 13:22:40', '2017-02-11 13:22:40', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce egestas dui quis tellus pharetra finibus. Suspendisse consequat maximus rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mattis varius posuere. Proin id sollicitudin eros. Maecenas consectetur leo nec orci finibus, laoreet semper libero molestie. Nulla sapien sapien, feugiat id arcu nec, vestibulum ornare magna. Sed orci neque, finibus nec volutpat et, dapibus ac lorem. Vivamus molestie eros consectetur augue volutpat porttitor. Suspendisse vitae pulvinar felis, eget mollis ante.\r\n\r\nIn nibh tellus, tristique sit amet sem non, egestas ullamcorper neque. Curabitur ullamcorper quam eget sapien vehicula, ut faucibus sapien porta. Nullam ornare eu justo vehicula fringilla. Integer ante odio, pellentesque sit amet posuere eget, congue in elit. Aenean tellus elit, accumsan quis consectetur eu, pharetra vel diam. Donec semper dignissim tortor, eu iaculis sapien bibendum nec. Maecenas ut nisi commodo, tempor eros nec, finibus urna. Praesent ornare urna nec velit tempus, quis sagittis leo fermentum. Fusce maximus, ligula et imperdiet pulvinar, nisl velit consectetur augue, ut porta enim eros vitae arcu. Quisque nunc metus, molestie sit amet scelerisque ut, sollicitudin sed mauris. Donec quis purus nulla. Quisque eleifend ullamcorper quam vel convallis. Praesent posuere, arcu eget semper interdum, tellus magna feugiat eros, non elementum lectus elit in neque. Phasellus pellentesque nisi ac lacus ornare interdum. Maecenas in pharetra lectus.', 'Services', '', 'publish', 'closed', 'closed', '', 'services', '', '', '2017-02-11 13:22:40', '2017-02-11 13:22:40', '', 0, 'http://localhost:8888/SPA/?page_id=12', 0, 'page', '', 0),
(13, 1, '2017-02-11 13:22:40', '2017-02-11 13:22:40', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce egestas dui quis tellus pharetra finibus. Suspendisse consequat maximus rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mattis varius posuere. Proin id sollicitudin eros. Maecenas consectetur leo nec orci finibus, laoreet semper libero molestie. Nulla sapien sapien, feugiat id arcu nec, vestibulum ornare magna. Sed orci neque, finibus nec volutpat et, dapibus ac lorem. Vivamus molestie eros consectetur augue volutpat porttitor. Suspendisse vitae pulvinar felis, eget mollis ante.\r\n\r\nIn nibh tellus, tristique sit amet sem non, egestas ullamcorper neque. Curabitur ullamcorper quam eget sapien vehicula, ut faucibus sapien porta. Nullam ornare eu justo vehicula fringilla. Integer ante odio, pellentesque sit amet posuere eget, congue in elit. Aenean tellus elit, accumsan quis consectetur eu, pharetra vel diam. Donec semper dignissim tortor, eu iaculis sapien bibendum nec. Maecenas ut nisi commodo, tempor eros nec, finibus urna. Praesent ornare urna nec velit tempus, quis sagittis leo fermentum. Fusce maximus, ligula et imperdiet pulvinar, nisl velit consectetur augue, ut porta enim eros vitae arcu. Quisque nunc metus, molestie sit amet scelerisque ut, sollicitudin sed mauris. Donec quis purus nulla. Quisque eleifend ullamcorper quam vel convallis. Praesent posuere, arcu eget semper interdum, tellus magna feugiat eros, non elementum lectus elit in neque. Phasellus pellentesque nisi ac lacus ornare interdum. Maecenas in pharetra lectus.', 'Services', '', 'inherit', 'closed', 'closed', '', '12-revision-v1', '', '', '2017-02-11 13:22:40', '2017-02-11 13:22:40', '', 12, 'http://localhost:8888/SPA/2017/02/11/12-revision-v1/', 0, 'revision', '', 0),
(14, 1, '2017-02-11 13:23:07', '2017-02-11 13:23:07', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce egestas dui quis tellus pharetra finibus. Suspendisse consequat maximus rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mattis varius posuere. Proin id sollicitudin eros. Maecenas consectetur leo nec orci finibus, laoreet semper libero molestie. Nulla sapien sapien, feugiat id arcu nec, vestibulum ornare magna. Sed orci neque, finibus nec volutpat et, dapibus ac lorem. Vivamus molestie eros consectetur augue volutpat porttitor. Suspendisse vitae pulvinar felis, eget mollis ante.\r\n\r\nIn nibh tellus, tristique sit amet sem non, egestas ullamcorper neque. Curabitur ullamcorper quam eget sapien vehicula, ut faucibus sapien porta. Nullam ornare eu justo vehicula fringilla. Integer ante odio, pellentesque sit amet posuere eget, congue in elit. Aenean tellus elit, accumsan quis consectetur eu, pharetra vel diam. Donec semper dignissim tortor, eu iaculis sapien bibendum nec. Maecenas ut nisi commodo, tempor eros nec, finibus urna. Praesent ornare urna nec velit tempus, quis sagittis leo fermentum. Fusce maximus, ligula et imperdiet pulvinar, nisl velit consectetur augue, ut porta enim eros vitae arcu. Quisque nunc metus, molestie sit amet scelerisque ut, sollicitudin sed mauris. Donec quis purus nulla. Quisque eleifend ullamcorper quam vel convallis. Praesent posuere, arcu eget semper interdum, tellus magna feugiat eros, non elementum lectus elit in neque. Phasellus pellentesque nisi ac lacus ornare interdum. Maecenas in pharetra lectus.', 'Events & Media', '', 'publish', 'closed', 'closed', '', 'events-media', '', '', '2017-02-11 13:23:07', '2017-02-11 13:23:07', '', 0, 'http://localhost:8888/SPA/?page_id=14', 0, 'page', '', 0),
(15, 1, '2017-02-11 13:23:07', '2017-02-11 13:23:07', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce egestas dui quis tellus pharetra finibus. Suspendisse consequat maximus rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mattis varius posuere. Proin id sollicitudin eros. Maecenas consectetur leo nec orci finibus, laoreet semper libero molestie. Nulla sapien sapien, feugiat id arcu nec, vestibulum ornare magna. Sed orci neque, finibus nec volutpat et, dapibus ac lorem. Vivamus molestie eros consectetur augue volutpat porttitor. Suspendisse vitae pulvinar felis, eget mollis ante.\r\n\r\nIn nibh tellus, tristique sit amet sem non, egestas ullamcorper neque. Curabitur ullamcorper quam eget sapien vehicula, ut faucibus sapien porta. Nullam ornare eu justo vehicula fringilla. Integer ante odio, pellentesque sit amet posuere eget, congue in elit. Aenean tellus elit, accumsan quis consectetur eu, pharetra vel diam. Donec semper dignissim tortor, eu iaculis sapien bibendum nec. Maecenas ut nisi commodo, tempor eros nec, finibus urna. Praesent ornare urna nec velit tempus, quis sagittis leo fermentum. Fusce maximus, ligula et imperdiet pulvinar, nisl velit consectetur augue, ut porta enim eros vitae arcu. Quisque nunc metus, molestie sit amet scelerisque ut, sollicitudin sed mauris. Donec quis purus nulla. Quisque eleifend ullamcorper quam vel convallis. Praesent posuere, arcu eget semper interdum, tellus magna feugiat eros, non elementum lectus elit in neque. Phasellus pellentesque nisi ac lacus ornare interdum. Maecenas in pharetra lectus.', 'Events & Media', '', 'inherit', 'closed', 'closed', '', '14-revision-v1', '', '', '2017-02-11 13:23:07', '2017-02-11 13:23:07', '', 14, 'http://localhost:8888/SPA/2017/02/11/14-revision-v1/', 0, 'revision', '', 0),
(16, 1, '2017-02-11 13:23:26', '2017-02-11 13:23:26', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce egestas dui quis tellus pharetra finibus. Suspendisse consequat maximus rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mattis varius posuere. Proin id sollicitudin eros. Maecenas consectetur leo nec orci finibus, laoreet semper libero molestie. Nulla sapien sapien, feugiat id arcu nec, vestibulum ornare magna. Sed orci neque, finibus nec volutpat et, dapibus ac lorem. Vivamus molestie eros consectetur augue volutpat porttitor. Suspendisse vitae pulvinar felis, eget mollis ante.\r\n\r\nIn nibh tellus, tristique sit amet sem non, egestas ullamcorper neque. Curabitur ullamcorper quam eget sapien vehicula, ut faucibus sapien porta. Nullam ornare eu justo vehicula fringilla. Integer ante odio, pellentesque sit amet posuere eget, congue in elit. Aenean tellus elit, accumsan quis consectetur eu, pharetra vel diam. Donec semper dignissim tortor, eu iaculis sapien bibendum nec. Maecenas ut nisi commodo, tempor eros nec, finibus urna. Praesent ornare urna nec velit tempus, quis sagittis leo fermentum. Fusce maximus, ligula et imperdiet pulvinar, nisl velit consectetur augue, ut porta enim eros vitae arcu. Quisque nunc metus, molestie sit amet scelerisque ut, sollicitudin sed mauris. Donec quis purus nulla. Quisque eleifend ullamcorper quam vel convallis. Praesent posuere, arcu eget semper interdum, tellus magna feugiat eros, non elementum lectus elit in neque. Phasellus pellentesque nisi ac lacus ornare interdum. Maecenas in pharetra lectus.', 'Case Studies', '', 'publish', 'closed', 'closed', '', 'case-studies', '', '', '2017-02-11 13:23:26', '2017-02-11 13:23:26', '', 0, 'http://localhost:8888/SPA/?page_id=16', 0, 'page', '', 0),
(17, 1, '2017-02-11 13:23:26', '2017-02-11 13:23:26', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce egestas dui quis tellus pharetra finibus. Suspendisse consequat maximus rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mattis varius posuere. Proin id sollicitudin eros. Maecenas consectetur leo nec orci finibus, laoreet semper libero molestie. Nulla sapien sapien, feugiat id arcu nec, vestibulum ornare magna. Sed orci neque, finibus nec volutpat et, dapibus ac lorem. Vivamus molestie eros consectetur augue volutpat porttitor. Suspendisse vitae pulvinar felis, eget mollis ante.\r\n\r\nIn nibh tellus, tristique sit amet sem non, egestas ullamcorper neque. Curabitur ullamcorper quam eget sapien vehicula, ut faucibus sapien porta. Nullam ornare eu justo vehicula fringilla. Integer ante odio, pellentesque sit amet posuere eget, congue in elit. Aenean tellus elit, accumsan quis consectetur eu, pharetra vel diam. Donec semper dignissim tortor, eu iaculis sapien bibendum nec. Maecenas ut nisi commodo, tempor eros nec, finibus urna. Praesent ornare urna nec velit tempus, quis sagittis leo fermentum. Fusce maximus, ligula et imperdiet pulvinar, nisl velit consectetur augue, ut porta enim eros vitae arcu. Quisque nunc metus, molestie sit amet scelerisque ut, sollicitudin sed mauris. Donec quis purus nulla. Quisque eleifend ullamcorper quam vel convallis. Praesent posuere, arcu eget semper interdum, tellus magna feugiat eros, non elementum lectus elit in neque. Phasellus pellentesque nisi ac lacus ornare interdum. Maecenas in pharetra lectus.', 'Case Studies', '', 'inherit', 'closed', 'closed', '', '16-revision-v1', '', '', '2017-02-11 13:23:26', '2017-02-11 13:23:26', '', 16, 'http://localhost:8888/SPA/2017/02/11/16-revision-v1/', 0, 'revision', '', 0),
(18, 1, '2017-02-11 13:23:44', '2017-02-11 13:23:44', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce egestas dui quis tellus pharetra finibus. Suspendisse consequat maximus rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mattis varius posuere. Proin id sollicitudin eros. Maecenas consectetur leo nec orci finibus, laoreet semper libero molestie. Nulla sapien sapien, feugiat id arcu nec, vestibulum ornare magna. Sed orci neque, finibus nec volutpat et, dapibus ac lorem. Vivamus molestie eros consectetur augue volutpat porttitor. Suspendisse vitae pulvinar felis, eget mollis ante.\r\n\r\nIn nibh tellus, tristique sit amet sem non, egestas ullamcorper neque. Curabitur ullamcorper quam eget sapien vehicula, ut faucibus sapien porta. Nullam ornare eu justo vehicula fringilla. Integer ante odio, pellentesque sit amet posuere eget, congue in elit. Aenean tellus elit, accumsan quis consectetur eu, pharetra vel diam. Donec semper dignissim tortor, eu iaculis sapien bibendum nec. Maecenas ut nisi commodo, tempor eros nec, finibus urna. Praesent ornare urna nec velit tempus, quis sagittis leo fermentum. Fusce maximus, ligula et imperdiet pulvinar, nisl velit consectetur augue, ut porta enim eros vitae arcu. Quisque nunc metus, molestie sit amet scelerisque ut, sollicitudin sed mauris. Donec quis purus nulla. Quisque eleifend ullamcorper quam vel convallis. Praesent posuere, arcu eget semper interdum, tellus magna feugiat eros, non elementum lectus elit in neque. Phasellus pellentesque nisi ac lacus ornare interdum. Maecenas in pharetra lectus.', 'Contact', '', 'publish', 'closed', 'closed', '', 'contact', '', '', '2017-02-11 13:23:44', '2017-02-11 13:23:44', '', 0, 'http://localhost:8888/SPA/?page_id=18', 0, 'page', '', 0),
(19, 1, '2017-02-11 13:23:44', '2017-02-11 13:23:44', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce egestas dui quis tellus pharetra finibus. Suspendisse consequat maximus rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras mattis varius posuere. Proin id sollicitudin eros. Maecenas consectetur leo nec orci finibus, laoreet semper libero molestie. Nulla sapien sapien, feugiat id arcu nec, vestibulum ornare magna. Sed orci neque, finibus nec volutpat et, dapibus ac lorem. Vivamus molestie eros consectetur augue volutpat porttitor. Suspendisse vitae pulvinar felis, eget mollis ante.\r\n\r\nIn nibh tellus, tristique sit amet sem non, egestas ullamcorper neque. Curabitur ullamcorper quam eget sapien vehicula, ut faucibus sapien porta. Nullam ornare eu justo vehicula fringilla. Integer ante odio, pellentesque sit amet posuere eget, congue in elit. Aenean tellus elit, accumsan quis consectetur eu, pharetra vel diam. Donec semper dignissim tortor, eu iaculis sapien bibendum nec. Maecenas ut nisi commodo, tempor eros nec, finibus urna. Praesent ornare urna nec velit tempus, quis sagittis leo fermentum. Fusce maximus, ligula et imperdiet pulvinar, nisl velit consectetur augue, ut porta enim eros vitae arcu. Quisque nunc metus, molestie sit amet scelerisque ut, sollicitudin sed mauris. Donec quis purus nulla. Quisque eleifend ullamcorper quam vel convallis. Praesent posuere, arcu eget semper interdum, tellus magna feugiat eros, non elementum lectus elit in neque. Phasellus pellentesque nisi ac lacus ornare interdum. Maecenas in pharetra lectus.', 'Contact', '', 'inherit', 'closed', 'closed', '', '18-revision-v1', '', '', '2017-02-11 13:23:44', '2017-02-11 13:23:44', '', 18, 'http://localhost:8888/SPA/2017/02/11/18-revision-v1/', 0, 'revision', '', 0),
(20, 1, '2017-02-11 13:24:42', '2017-02-11 13:24:42', '', 'Home', '', 'publish', 'closed', 'closed', '', 'home', '', '', '2017-02-11 13:24:42', '2017-02-11 13:24:42', '', 0, 'http://localhost:8888/SPA/?p=20', 1, 'nav_menu_item', '', 0),
(21, 1, '2017-02-11 13:24:42', '2017-02-11 13:24:42', ' ', '', '', 'publish', 'closed', 'closed', '', '21', '', '', '2017-02-11 13:24:42', '2017-02-11 13:24:42', '', 0, 'http://localhost:8888/SPA/?p=21', 2, 'nav_menu_item', '', 0),
(22, 1, '2017-02-11 13:24:42', '2017-02-11 13:24:42', ' ', '', '', 'publish', 'closed', 'closed', '', '22', '', '', '2017-02-11 13:24:42', '2017-02-11 13:24:42', '', 0, 'http://localhost:8888/SPA/?p=22', 5, 'nav_menu_item', '', 0),
(23, 1, '2017-02-11 13:24:42', '2017-02-11 13:24:42', ' ', '', '', 'publish', 'closed', 'closed', '', '23', '', '', '2017-02-11 13:24:42', '2017-02-11 13:24:42', '', 0, 'http://localhost:8888/SPA/?p=23', 6, 'nav_menu_item', '', 0),
(24, 1, '2017-02-11 13:24:42', '2017-02-11 13:24:42', ' ', '', '', 'publish', 'closed', 'closed', '', '24', '', '', '2017-02-11 13:24:42', '2017-02-11 13:24:42', '', 0, 'http://localhost:8888/SPA/?p=24', 4, 'nav_menu_item', '', 0),
(25, 1, '2017-02-11 13:24:03', '0000-00-00 00:00:00', ' ', '', '', 'draft', 'closed', 'closed', '', '', '', '', '2017-02-11 13:24:03', '0000-00-00 00:00:00', '', 0, 'http://localhost:8888/SPA/?p=25', 1, 'nav_menu_item', '', 0),
(26, 1, '2017-02-11 13:24:42', '2017-02-11 13:24:42', ' ', '', '', 'publish', 'closed', 'closed', '', '26', '', '', '2017-02-11 13:24:42', '2017-02-11 13:24:42', '', 0, 'http://localhost:8888/SPA/?p=26', 3, 'nav_menu_item', '', 0),
(27, 1, '2017-02-11 13:28:55', '2017-02-11 13:28:55', '', 'Home', '', 'publish', 'closed', 'closed', '', 'home', '', '', '2017-02-11 13:28:55', '2017-02-11 13:28:55', '', 0, 'http://localhost:8888/SPA/?page_id=27', 0, 'page', '', 0),
(28, 1, '2017-02-11 13:28:55', '2017-02-11 13:28:55', '', 'Home', '', 'inherit', 'closed', 'closed', '', '27-revision-v1', '', '', '2017-02-11 13:28:55', '2017-02-11 13:28:55', '', 27, 'http://localhost:8888/SPA/2017/02/11/27-revision-v1/', 0, 'revision', '', 0),
(29, 1, '2017-02-11 13:29:03', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2017-02-11 13:29:03', '0000-00-00 00:00:00', '', 0, 'http://localhost:8888/SPA/?p=29', 0, 'post', '', 0),
(30, 1, '2017-02-11 14:35:01', '0000-00-00 00:00:00', '{\n    \"wp-experts::smof_data[top_email]\": {\n        \"value\": \"sarah@sarahpiddington\",\n        \"type\": \"theme_mod\",\n        \"user_id\": 1\n    }\n}', '', '', 'auto-draft', 'closed', 'closed', '', '92f86787-80f6-4f1b-afd9-fbf5d23b7e32', '', '', '2017-02-11 14:39:33', '2017-02-11 14:39:33', '', 0, 'http://localhost:8888/SPA/?p=30', 0, 'customize_changeset', '', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `wp_posts`
--
ALTER TABLE `wp_posts`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `post_name` (`post_name`(191)),
  ADD KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`),
  ADD KEY `post_parent` (`post_parent`),
  ADD KEY `post_author` (`post_author`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `wp_posts`
--
ALTER TABLE `wp_posts`
  MODIFY `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
